### ISSUE TITLE
Error in Xtest[, ind_ref] : (subscript) logical subscript too long

### ISSUE THREAD

**Issue by bbitarello** [YangLabHKUST/XPASS#4]
Hi,
I ran the following command:

`fit_obj2<-XPASS(file_z1 =ss_in[1],file_z2 = ss_in[2],file_ref1 = l[1],
                file_ref2 =  l[2],
                file_cov1 = cov_in[1],file_cov2 = cov_in[2],
                file_predGeno = val,
                compPRS=T,
                pop = "EAS",sd_method="LD_block",compPosMean = T,
                file_out = glue::glue("output/{pheno}_{ss[1]}_{ss[2]}"))
`

And got the following error:

`Error in Xtest[, ind_ref] : (subscript) logical subscript too long
Calls: <Anonymous> -> system.time -> XPASS
In addition: Warning message:
In ref1_info$A1 != test_info$A1 :
  longer object length is not a multiple of shorter object length`
  
 It seems like this is due to the test (validation) data having a different number of SNPs than one of the reference datasets. Do we need to filter all the datasets beforehand to have the same SNPs? I thought the script did that in the same way that it finds the intersection between target and auxiliary datasets. Please let me know. Thank you

**Comment by mxcai** [comment]
Hi,

The XPASS function has the internal filtering step so that all datasets are harmonized and you don't need to match SNPs manually beforehand. I have tested several situations where the files are not matched but failed to replicate this error. Could you provide the log generated by running the above codes? 

Best,
Mingxuan

**Comment by bbitarello** [comment]
Hi Mingxuan, 

looking more carefully, the main error is about the logical subscript being too long. Here is the R code:

`fit_obj<-XPASS(file_z1 =ss_in[1],file_z2 = ss_in[2],file_ref1 = l[1],
                file_ref2 =  l[2],
                file_cov1 = cov_in[1],file_cov2 = cov_in[2],
                file_predGeno = val,
                compPRS=T,
                pop = "EAS",sd_method="LD_block",compPosMean = T,
                file_out = glue::glue("output/{pheno}_{ss[1]}_{ss[2]}"))`
                
                               
Output in log file:

Summary statistics file 1: tmp-dir/file1b100376dfd02_ss_1.txt
Summary statistics file 2: tmp-dir/file1b100376dfd02_ss_2.txt
Reference file 1: to_delete/1000g_all_EAS_hg38
Reference file 2: to_delete/UKB_EUR_hg38_filt
Covariates file 1: to_delete/1000g_all_EAS_hg38.eigenvec
Covariates file 2: to_delete/UKB_EUR_hg38_filt.eigenvec
Test genotype file : to_delete/UKB_CHI_hg38
Reading data from summary statisitcs...
963401 and 1048926 SNPs found in summary statistics files 1 and 2.
Reading SNP info from reference panels...
2697305 and 1053783 SNPs found in reference panel 1 and 2.
Reading SNP info from test genotype file...
632520 SNPs found in test file.
133605 SNPs are matched in all files.
0 SNPs are removed because of ambiguity; 133605 SNPs remained.
Calculating kinship matrix from the both reference panels...
2112 SNPs are removed because of no variation; 131493 SNPs remained.
0 SNPs have different minor alleles in population 1, z-scores are corrected according to reference panel.
0 SNPs have different minor alleles in population 2, z-scores are corrected according to reference panel.
Assigning SNPs to LD Blocks...
Calculate PVE...
             h1         h2        h12        rho
[1,] 0.37847412 0.49999588 0.30917449 0.71072622
[2,] 0.03244267 0.04599762 0.02228796 0.03769259
Compute posterior mean from  1340  blocks ...
Compute posterior mean from two datasets.
Block 1 / 1340  finished.
Compute posterior mean from two datasets.
[skipping the lines for the other blocks]
Block 1340 / 1340  finished.
Predicting PRS from test genotypes...

At this point the code crashed and the error message, logged in a separate file, is:

`Error in Xtest[, ind_ref] : (subscript) logical subscript too long
Calls: <Anonymous> -> system.time -> XPASS
In addition: Warning message:
In ref1_info$A1 != test_info$A1 :
  longer object length is not a multiple of shorter object length
Timing stopped at: 1.1e+04 66.45 1.109e+04
Execution halted                
                `

**Comment by mxcai** [comment]
Hi,

Thank you for your information. The error is due to a bug where the SNPs with zero variance are not removed from the bim matrix of test genotypes. It is now fixed. Please re-install the package from GitHub and try again.

Thank you,
Mingxuan

**Comment by bbitarello** [comment]
Hi Mingxuan,
this problem is apparently solved! Thank you
